# Generated by Django 6.1.1 on 2026-09-30 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_booking_eventinteraction_savedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularityPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_label', models.BooleanField()),
                ('predicted_probability', models.FloatField()),
                ('model_version', models.CharField(max_length=50)),
                ('predicted_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_prediction', to='events.event')),
            ],
        ),
    ]
